spring.application.name=sb-ecom
server.port=9090

# H2 Console'u aktif et (Taray?c?dan girmek için)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Veritaban? ba?lant? bilgilerini sabitle
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=ibrahim
spring.datasource.password=

# Hibernate ve SQL loglar?n? zorla göster
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE